### ISSUE TITLE
Статистика

### ISSUE THREAD

**Issue by lexaSvarshik** [BCanary/AutoVinchik#1]
В папке с файлами есть файл статистики, как и на странице гитхаба статистика есть. Но программа никакой статистики не пишет. Неплохо было бы включить эту вещь обратно.

**Comment by BCanary** [comment]
Упс... Файл stat.txt вообще не должен был быть запушен. Было это дело реализовано через выгрузку всех сообщений в один файл и анализ файла на поиск одинаковых вхождений и их подсчёт.

Я не посчитал нужным это включать, но думаю дописать небольшой модуль для этой задачи.

**Comment by lexaSvarshik** [comment]
Окей, неплохо было бы.

**Comment by BCanary** [comment]
Готово, надеюсь ничего не поломал (Поломал кстати)

Создаётся так же файл messages.txt в котором содержится выгрузка всех указанных сообщений от бота. Можно уже поверх него использовать всякие другие программы для анализа.

![Screenshot_4](https://user-images.githubusercontent.com/59798021/209478449-a5971cec-f1d2-4bfb-80dc-368b2fd86f7d.png)
![Screenshot_5](https://user-images.githubusercontent.com/59798021/209478453-69bafea1-1d0d-457e-82b4-1e5e0b90b90f.png)
