### ISSUE TITLE
Скрипт отвечает на собственные сообщения

### ISSUE THREAD

**Issue by lexaSvarshik** [BCanary/AutoVinchik#5]
По неизвестным причинам несколько раз отвечал на собственные сообщения:
![изображение](https://user-images.githubusercontent.com/96281939/212481548-72fa2cf5-2cd3-4c94-acb7-a82199b6b595.png)

Но в `clear_messages.txt` таких сообщений (эмоджи палец вниз) не обнаружено.

**Comment by BCanary** [comment]
Какая задержка для тг стоит? Бот считывает последнее сообщение. Рекомендую увеличить задержку.
