### ISSUE TITLE
Ошибка функционала

### ISSUE THREAD

**Issue by DoodleModder** [BCanary/AutoVinchik#6]
Я может конечно чего не понимаю (в питонах этих ваших новичок), но по какой-то причине прога шлет в вк цифру "3" при нажатии enter (когда надо пропустить анкету). А на тройку у них там отключение своей анкеты или подача жалобы. Короче, не та команда выдается. Не ясно, дело в каких-то новых изменениях винчика может, но сейчас не работает.

**Comment by BCanary** [comment]
Всё работает, в режим поиска сначала войдите, а потом запускайте. Т.е. включите "Смотреть анкеты".
 
 
 
![изображение](https://github.com/BCanary/AutoVinchik/assets/59798021/d8cff44b-c51c-4fac-be2d-8a8adf002e7a)
![изображение](https://github.com/BCanary/AutoVinchik/assets/59798021/ee8ba9ba-e8ce-40f0-b1f6-2d3acdd4babb)

**Comment by BCanary** [comment]
Если поможет, отпишите, я Issue закрою. У меня во всяком случае в ВК всё работает, я код 2-3 года как не менял, у них тоже ничего особо не поменялось.
