### ISSUE TITLE
NameError name client is not defined

### ISSUE THREAD

**Issue by NeArFeCo** [BCanary/AutoVinchik#7]
![image](https://github.com/BCanary/AutoVinchik/assets/119441851/9b72d98d-1446-42ac-9e84-c79e65086cc2)
Помоги пожалуйста решить проблему

**Comment by NeArFeCo** [comment]
Пробовал разные аккаунты всё равно вылетает

**Comment by NeArFeCo** [comment]
Пробовал переустановить после запуска анкет в тг выкидывает с аккаунта на пк в веб версии и с телефона

**Comment by BCanary** [comment]
![изображение](https://github.com/BCanary/AutoVinchik/assets/59798021/9945307c-f820-4e54-86f4-d45b1e8e8702)
У вас скорее всего ключ телеграм не подключен. Скиньте, что выводится в начале, если там телеграм красным выделен, то это значит, что телеграм поиск работать и не будет.
![изображение](https://github.com/BCanary/AutoVinchik/assets/59798021/cc625e43-3ee9-4a6a-9c93-ec22227396c7)
Токен телеграм настроен у вас?

**Comment by NeArFeCo** [comment]
А что там настраивать

**Comment by NeArFeCo** [comment]
Я просто создал App configuration и от туда скопировал значения

**Comment by NeArFeCo** [comment]
Теперь я вообще в аккаунт войти не могу)

**Comment by NeArFeCo** [comment]
Я подключил токен все дела. Но всё равно вылетает

**Comment by BCanary** [comment]
При первом запуске конфиг автоматически создаётся, самому ничего не надо создавать. Просто через настройки внутри приложения вбить ключи и перезапустить приложение, чтобы ключи подключились.

Подробнее опишите что, где и как делали, иначе помочь не смогу. Платформа, выводится ли зелёным "Подключен ключ" при запуске, скрин из конфигурации (ключ там по умолчанию скрыт наполовину, так что скрин делать можно). По инструкции из README на главной странице.

**Comment by NeArFeCo** [comment]
![image](https://github.com/BCanary/AutoVinchik/assets/119441851/f1e5b834-9e1d-44bd-a45e-3fd4e37e0a1c)
Вот я ввожу свой номер и потом код и всё вылетает

**Comment by NeArFeCo** [comment]
Ну ни когда я ввожу код а когда нажимаю поиск по телеграмму или же комбинированный

**Comment by NeArFeCo** [comment]
https://github.com/BCanary/AutoVinchik/assets/119441851/a0d0b899-7dca-417c-ad00-106750cceeac

**Comment by NeArFeCo** [comment]
Короче я починил. Только хз как =-)

**Comment by BCanary** [comment]
Попробуйте новый ключ создать в телеграме. "AuthKeyUnregisteredError('The key is not registered in the system')" -- это сам телеграм ругается, что с ключом что-то не так.

Отсюда же ключ берёте? https://my.telegram.org/apps

Ключ до этого ещё где-то использовался? Можно попробовать удалить из владки Active sessions ключ и ещё раз попытаться войти с этим ключом.

![изображение](https://github.com/BCanary/AutoVinchik/assets/59798021/bc5940aa-2ddc-4905-bf98-0e2cfa164596)
![изображение](https://github.com/BCanary/AutoVinchik/assets/59798021/7608d2ab-0a25-49a2-912c-312824f4518c)

Я вот залогинится смог (скачал репозиторий с нуля). _Однако там приложение вылетело из-за идиотской рекламы дайвинчика, но я приложение уже давно не обновлял и не собираюсь. С этим только смириться и пропускать рекламу вручную._

![изображение](https://github.com/BCanary/AutoVinchik/assets/59798021/740a1968-c6c8-4c5a-95b8-f35cadb54c93)

**Comment by NeArFeCo** [comment]
> Попробуйте новый ключ создать в телеграме. "AuthKeyUnregisteredError('The key is not registered in the system')" -- это сам телеграм ругается, что с ключом что-то не так.
> 
> Отсюда же ключ берёте? https://my.telegram.org/apps
> 
> Ключ до этого ещё где-то использовался? Можно попробовать удалить из владки Active sessions ключ и ещё раз попытаться войти с этим ключом.
> 
> ![изображение](https://private-user-images.githubusercontent.com/59798021/347010327-bc5940aa-2ddc-4905-bf98-0e2cfa164596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDAwNDAsIm5iZiI6MTcyMDYzOTc0MCwicGF0aCI6Ii81OTc5ODAyMS8zNDcwMTAzMjctYmM1OTQwYWEtMmRkYy00OTA1LWJmOTgtMGUyY2ZhMTY0NTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE5MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NzI5N2EwYjUyYWQ1NGI2MDdiMDhiOWJiNjJmYjFmN2FjMWNkZTE4MjA4ZjJkNTU3MTQ0M2U0ZjI5OTc5NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gRE-b-udYOqlsX5ZidS15Ygmk5BI13OHVYK6UMrfrw8) ![изображение](https://private-user-images.githubusercontent.com/59798021/347012067-7608d2ab-0a25-49a2-912c-312824f4518c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDAwNDAsIm5iZiI6MTcyMDYzOTc0MCwicGF0aCI6Ii81OTc5ODAyMS8zNDcwMTIwNjctNzYwOGQyYWItMGEyNS00OWEyLTkxMmMtMzEyODI0ZjQ1MThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE5MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGFiZGJhMzZhZjA0YjExOWJkNTBhOGJmYTY1NGUzMWFjN2Y2N2YwOTFhMWZjYWVjMjgxOThlMGZhZmFiMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bfcc1z_U__XgtxLpwp_5jYVl9W2cg9RfDk9EZFG1IwI)
> 
> Я вот залогинится смог (скачал репозиторий с нуля). _Однако там приложение вылетело из-за идиотской рекламы дайвинчика, но я приложение уже давно не обновлял и не собираюсь. С этим только смириться и пропускать рекламу вручную._
> 
> ![изображение](https://private-user-images.githubusercontent.com/59798021/347011868-740a1968-c6c8-4c5a-95b8-f35cadb54c93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDAwNDAsIm5iZiI6MTcyMDYzOTc0MCwicGF0aCI6Ii81OTc5ODAyMS8zNDcwMTE4NjgtNzQwYTE5NjgtYzZjOC00YzVhLTk1YjgtZjM1Y2FkYjU0YzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE5MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjY2RiYzUyOGU3NDg5YmNiMmQ0MTE4Y2M1Mzg2YTQ3NDg3NWEyYmZjNmI1Mzc2MjkyMWJiM2U5NTNhNjk0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0w_v1s4njSPw3kvsJEV3wcWqvuv99VjavMydHzJp5j4)

У меня в аctive session только телефон и мой комп

**Comment by BCanary** [comment]
После подключения к телеграму через программу должно появится что-то типо того
![изображение](https://github.com/user-attachments/assets/ef9de5d1-5638-4d21-b2d1-4ef95ec0a728)

Я когда вставляю два своих ключа у меня спокойно всё логинится. Какая-то проблема на стороне телеграма...
![изображение](https://github.com/user-attachments/assets/00defc15-54ba-4c20-b45e-220131e5d05d)

Есть вариант, как я прочитал на форумах, попробовать удалить файл сессии перед запуском программы (возможно сессия истекла...)
![изображение](https://github.com/user-attachments/assets/831a7106-b563-4615-a7ff-8740193cda10)

После удаления этого файла повторно зайти, вбить телефон и код из чата телеграма.
