### ISSUE TITLE
постоянные вылеты

### ISSUE THREAD

**Issue by kaj3er** [BCanary/AutoVinchik#8]
выбрасывает и с устройства и с так скажем бота

**Comment by BCanary** [comment]
Подробнее. Всё работает лично у меня. 
![Screenshot_20241217_184354_com termux](https://github.com/user-attachments/assets/d5cedc96-eaf3-47ff-8c6f-8ea9203a81cc)

**Comment by kaj3er** [comment]
Сейчас скотном не подкреплю но примерно через 10-11 минут после логина в боте просто выбрасывает из аккаунта все делал на тг , так же сначала подумал что это я напортачил в поле ввода номера или idбота по типу по типу с номером вылеты а id бота я даже не знаю как получить вот как то так

**Comment by BCanary** [comment]
Я бы с вылетом телеграм может и помог, но они ввели обязательную верификацию видеокружком, я от этой процедуры отказываюсь, так что обновлений в части касающейся функционала телеграм не будет.

Будет информативнее, если получится прикрепить лог ошибки, или если что то ещё выводится, подумаю, может что-то получится.

**Comment by kaj3er** [comment]
кароче бот сейчас работает нормально только на вк? если да то ладно просто мне скорее всего изза подозрительной активности сеансы падают в тг

**Comment by BCanary** [comment]
Может быть и так, в вк у меня по крайней мере были сообщения от дайвинчика служебные (ака "подпишитесь на паблик"), которые ломали скрипт. Фиксится перезапуском.

В тг может тоже работает, можно попробовать снизить скорость отправки сообщений для тг в конфигурации.

**Comment by kaj3er** [comment]
Пробовал до 3 секунд как в самописном боте "тупой подсчет цветов на области" все равно так что я наверное ВК версию потыкаю и если не получится напишу, спасиб кстати за быстрый ответ

**Comment by BCanary** [comment]
Кое что интересное нашёл, кто то форкнул или с нуля написал тоже самое что у меня. Можно это попробовать:
https://github.com/trottling/QueVinchik/

**Comment by BCanary** [comment]
Он как раз на телеграм настроен

**Comment by kaj3er** [comment]
ну в общем тыкаю сижу второй варик если честно пока что есть только боль

**Comment by kaj3er** [comment]
слушай в принцепе я его натыкал но скажем так есть предположение что в твоем случае задержку 10 нужно ставить у него всё работет на новых библиотеках это только для тг а для вк с пол тычка всё заработало с задержкой 6
